// Multi-language translations for Vidhub APK Distribution
const translations = {
  en: {
    title: "Vidhub",
    tagline: "Stream in Style",
    subtitle: "Watch Anywhere, Anytime",
    download: "Download App",
    explore: "Explore Features",
    loading: "Loading...",
    downloading: "Downloading Vidhub...",
    downloadStarted: "Download started! Check your downloads folder.",
    downloadError: "Download failed. Please try again.",
    features: "Powerful Features",
    featuresSub: "Everything you need for amazing experience",
    heroBadge: "Hot drops · Unlimited passion",
    heroTitle: "Feel the heat.<br>Stream in style.",
    heroDesc: "Immerse yourself in exclusive series, heart-racing originals, and cinema-grade thrills. Get the Vidhub app now and ignite your watchlist — 7 days fiery trial.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "Get the App",
    btnInstall: "Install Now",
    sectionTitle: "Sizzling now · exclusive previews",
    bannerTitle: "Vidhub+ Membership",
    bannerDesc: "Offline mode, HDR10+, and unlimited downloads. Only inside our official app. Join the movement.",
    footerText: "© 2025 Vidhub Streaming — where stories burn bright. All rights reserved.",
    footerExtra: "4K HDR | No ads on mobile app",
    toastDefault: "🔥 Download Vidhub app — unlock hot exclusives & offline mode!",
    toastExclusive: "❤️‍🔥 This content is exclusive to the Vidhub app — get it now!",
    trending: "Trending 🔥",
    fresh: "Fresh pick",
    apkSize: "APK • XX MB",
    statUsers: "Happy Users",
    statVideos: "Downloads",
    statSync: "Always Online",
    feat1Title: "4K HDR Streaming",
    feat1Desc: "Crystal clear quality with HDR10+ support for stunning visuals",
    feat2Title: "Offline Downloads",
    feat2Desc: "Download your favorites and watch anywhere without internet",
    feat3Title: "Exclusive Originals",
    feat3Desc: "Award-winning originals you won't find anywhere else",
    feat4Title: "No Ads",
    feat4Desc: "Uninterrupted viewing experience on all devices",
    feat5Title: "Multi-Device",
    feat5Desc: "Watch on phone, tablet, TV, or web browser",
    feat6Title: "Live TV Channels",
    feat6Desc: "Access to 100+ live TV channels and sports",
    feat7Title: "Family Sharing",
    feat7Desc: "Share your account with up to 6 family members",
    feat8Title: "Kids Mode",
    feat8Desc: "Safe viewing experience with parental controls",
    feat9Title: "Downloads",
    feat9Desc: "Download up to 100 titles for offline viewing",
    feat10Title: "Skip Intro",
    feat10Desc: "Skip opening credits and get straight to the action",
    feat11Title: "Audio Descriptions",
    feat11Desc: "Audio descriptions for visually impaired viewers",
    feat12Title: "New Releases",
    feat12Desc: "New movies and episodes added every week"
  },
  es: {
    title: "Vidhub",
    tagline: "Transmite con Estilo",
    subtitle: "Mira en Cualquier Lugar",
    download: "Descargar App",
    explore: "Explorar Características",
    loading: "Cargando...",
    downloading: "Descargando Vidhub...",
    downloadStarted: "¡Descarga iniciada! Revisa tu carpeta de descargas.",
    downloadError: "Descarga fallida. Por favor, inténtelo de nuevo.",
    features: "Características Potentes",
    featuresSub: "Todo lo que necesitas para una experiencia increíble",
    heroBadge: "Lanzamientos candentes · Pasión ilimitada",
    heroTitle: "Siente el calor.<br>Transmite con estilo.",
    heroDesc: "Sumérgete en series exclusivas, originales emocionantes y emociones de calidad cinematográfica. Obtén la aplicación Vidhub ahora y enciende tu lista de reproducción — 7 días de prueba intensa.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "Obtener la App",
    btnInstall: "Instalar Ahora",
    sectionTitle: "Ardiendo ahora · vistas previas exclusivas",
    bannerTitle: "Membresía Vidhub+",
    bannerDesc: "Modo sin conexión, HDR10+ y descargas ilimitadas. Solo dentro de nuestra aplicación oficial. Únete al movimiento.",
    footerText: "© 2025 Vidhub Streaming — donde las historias arden intensamente. Todos los derechos reservados.",
    footerExtra: "4K HDR | Sin anuncios en la aplicación móvil",
    toastDefault: "🔥 ¡Descarga la aplicación Vidhub — desbloquea exclusivos candentes y modo sin conexión!",
    toastExclusive: "❤️‍🔥 Este contenido es exclusivo de la aplicación Vidhub — ¡consíguelo ahora!",
    trending: "Tendencia 🔥",
    fresh: "Novedad",
    apkSize: "APK • XX MB",
    statUsers: "Usuarios Felices",
    statVideos: "Descargas",
    statSync: "Siempre Online",
    feat1Title: "Streaming en 4K HDR",
    feat1Desc: "Calidad cristalina con soporte HDR10+ para visuales impresionantes",
    feat2Title: "Descargas Sin Conexión",
    feat2Desc: "Descarga tus favoritos y mira donde sea sin internet",
    feat3Title: "Originales Exclusivos",
    feat3Desc: "Originales premiados que no encontrarás en ningún otro lugar",
    feat4Title: "Sin Anuncios",
    feat4Desc: "Experiencia de visualización ininterrumpida en todos los dispositivos",
    feat5Title: "Multi-Dispositivo",
    feat5Desc: "Mira en teléfono, tableta, TV o navegador web",
    feat6Title: "Canales de TV en Vivo",
    feat6Desc: "Acceso a más de 100 canales de TV en vivo y deportes",
    feat7Title: "Compartir en Familia",
    feat7Desc: "Comparte tu cuenta con hasta 6 miembros de la familia",
    feat8Title: "Modo Niños",
    feat8Desc: "Experiencia de visualización segura con controles parentales",
    feat9Title: "Descargas",
    feat9Desc: "Descarga hasta 100 títulos para ver sin conexión",
    feat10Title: "Saltar Intro",
    feat10Desc: "Salta los créditos de apertura y ve directo a la acción",
    feat11Title: "Descripciones de Audio",
    feat11Desc: "Descripciones de audio para espectadores con discapacidad visual",
    feat12Title: "Nuevos Lanzamientos",
    feat12Desc: "Nuevas películas y episodios añadidos cada semana"
  },
  fr: {
    title: "Vidhub",
    tagline: "Diffusez avec Style",
    subtitle: "Regardez N'importe Où",
    download: "Télécharger App",
    explore: "Explorer les Fonctionnalités",
    loading: "Chargement...",
    downloading: "Téléchargement Vidhub...",
    downloadStarted: "Téléchargement démarré! Vérifiez votre dossier de téléchargement.",
    downloadError: "Téléchargement échoué. Veuillez réessayer.",
    features: "Fonctionnalités Puissantes",
    featuresSub: "Tout ce dont vous avez besoin pour une expérience incroyable",
    heroBadge: "Nouveautés chaudes · Passion illimitée",
    heroTitle: "Ressentez la chaleur.<br>Diffusez avec style.",
    heroDesc: "Plongez dans des séries exclusives, des originaux palpitants et des frissons de qualité cinématographique. Obtenez l'application Vidhub maintenant et allumez votre liste de lecture — 7 jours d'essai intense.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "Obtenir l'App",
    btnInstall: "Installer Maintenant",
    sectionTitle: "Brûlant maintenant · aperçus exclusifs",
    bannerTitle: "Adhésion Vidhub+",
    bannerDesc: "Mode hors ligne, HDR10+ et téléchargements illimités. Uniquement dans notre application officielle. Rejoignez le mouvement.",
    footerText: "© 2025 Vidhub Streaming — où les histoires brûlent fort. Tous droits réservés.",
    footerExtra: "4K HDR | Pas de publicités sur l'application mobile",
    toastDefault: "🔥 Téléchargez l'application Vidhub — débloquez des exclusivités brûlantes et le mode hors connexion !",
    toastExclusive: "❤️‍🔥 Ce contenu est exclusif à l'application Vidhub — obtenez-le maintenant !",
    trending: "Tendance 🔥",
    fresh: "Nouveau",
    apkSize: "APK • XX MB",
    statUsers: "Utilisateurs Heureux",
    statVideos: "Téléchargements",
    statSync: "Toujours en Ligne",
    feat1Title: "Streaming 4K HDR",
    feat1Desc: "Qualité cristalline avec support HDR10+ pour des visuels époustouflants",
    feat2Title: "Téléchargements Hors Ligne",
    feat2Desc: "Téléchargez vos favoris et regardez n'importe où sans internet",
    feat3Title: "Originaux Exclusifs",
    feat3Desc: "Originaux primés que vous ne trouverez nulle part ailleurs",
    feat4Title: "Sans Publicités",
    feat4Desc: "Expérience de visualisation ininterrompue sur tous les appareils",
    feat5Title: "Multi-Appareil",
    feat5Desc: "Regardez sur téléphone, tablette, TV ou navigateur web",
    feat6Title: "Chaînes TV en Direct",
    feat6Desc: "Accès à plus de 100 chaînes TV en direct et sports",
    feat7Title: "Partage Famille",
    feat7Desc: "Partagez votre compte avec jusqu'à 6 membres de famille",
    feat8Title: "Mode Enfants",
    feat8Desc: "Expérience de visualisation sécurisée avec contrôles parentaux",
    feat9Title: "Téléchargements",
    feat9Desc: "Téléchargez jusqu'à 100 titres pour regarder hors ligne",
    feat10Title: "Skip Intro",
    feat10Desc: "Sautez les génériques et allez directement à l'action",
    feat11Title: "Descriptions Audio",
    feat11Desc: "Descriptions audio pour les spectateurs malvoyants",
    feat12Title: "Nouvelles Sorties",
    feat12Desc: "Nouveaux films et épisodes ajoutés chaque semaine"
  },
  de: {
    title: "Vidhub",
    tagline: "Streamen mit Stil",
    subtitle: "Überall Jederzeit",
    download: "App Herunterladen",
    explore: "Funktionen Erkunden",
    loading: "Laden...",
    downloading: "Vidhub herunterladen...",
    downloadStarted: "Download gestartet! Überprüfen Sie Ihren Download-Ordner.",
    downloadError: "Download fehlgeschlagen. Bitte versuchen Sie es erneut.",
    features: "Leistungsstarke Funktionen",
    featuresSub: "Alles was Sie für eine tolle Erfahrung brauchen",
    heroBadge: "Heiße Drops · Unbegrenzte Leidenschaft",
    heroTitle: "Spüren Sie die Hitze.<br>Streamen Sie mit Stil.",
    heroDesc: "Tauchen Sie ein in exklusive Serien, herzrasende Originale und kinoreife Thrills. Holen Sie sich die Vidhub App jetzt und zünden Sie Ihre Watchlist an — 7 Tage intensive Testphase.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "App Holen",
    btnInstall: "Jetzt Installieren",
    sectionTitle: "Heiß jetzt · exklusive Vorschauen",
    bannerTitle: "Vidhub+ Mitgliedschaft",
    bannerDesc: "Offline-Modus, HDR10+ und unbegrenzte Downloads. Nur in unserer offiziellen App. Schließen Sie sich der Bewegung an.",
    footerText: "© 2025 Vidhub Streaming — wo Geschichten hell brennen. Alle Rechte vorbehalten.",
    footerExtra: "4K HDR | Keine Werbung in der mobilen App",
    toastDefault: "🔥 Vidhub App herunterladen — heiße Exklusivitäten & Offline-Modus freischalten!",
    toastExclusive: "❤️‍🔥 Dieser Inhalt ist exklusiv für die Vidhub App — holen Sie sie sich jetzt!",
    trending: "Im Trend 🔥",
    fresh: "Neue Auswahl",
    apkSize: "APK • XX MB",
    statUsers: "Glückliche Benutzer",
    statVideos: "Downloads",
    statSync: "Immer Online",
    feat1Title: "4K HDR Streaming",
    feat1Desc: "Kristallklare Qualität mit HDR10+ Unterstützung für atemberaubende Bilder",
    feat2Title: "Offline Downloads",
    feat2Desc: "Laden Sie Ihre Favoriten herunter und schauen Sie überall ohne Internet",
    feat3Title: "Exklusive Originale",
    feat3Desc: "Ausgezeichnete Originale, die Sie nirgendwo anders finden",
    feat4Title: "Keine Werbung",
    feat4Desc: "Unterbrechungsfreies Seherlebnis auf allen Geräten",
    feat5Title: "Multi-Gerät",
    feat5Desc: "Schauen Sie auf Telefon, Tablet, TV oder Webbrowser",
    feat6Title: "Live-TV-Kanäle",
    feat6Desc: "Zugriff auf über 100 Live-TV-Kanäle und Sport",
    feat7Title: " Familienfreigabe",
    feat7Desc: "Teilen Sie Ihr Konto mit bis zu 6 Familienmitgliedern",
    feat8Title: "Kindermodus",
    feat8Desc: "Sicheres Seherlebnis mit Elternkontrollen",
    feat9Title: "Downloads",
    feat9Desc: "Laden Sie bis zu 100 Titel für das Offline-Ansehen herunter",
    feat10Title: "Intro Überspringen",
    feat10Desc: "Überspringen Sie den Abspann und kommen Sie direkt zum Action",
    feat11Title: "Audiobeschreibungen",
    feat11Desc: "Audiobeschreibungen für sehbehinderte Zuschauer",
    feat12Title: "Neuerscheinungen",
    feat12Desc: "Jede Woche werden neue Filme und Episoden hinzugefügt"
  },
  zh: {
    title: "Vidhub",
    tagline: "时尚流媒体",
    subtitle: "随时随地观看",
    download: "下载应用",
    explore: "探索功能",
    loading: "加载中...",
    downloading: "正在下载 Vidhub...",
    downloadStarted: "下载已开始！请检查您的下载文件夹。",
    downloadError: "下载失败。请重试。",
    features: "强大功能",
    featuresSub: "出色体验所需的一切",
    heroBadge: "热门内容 · 无限激情",
    heroTitle: "感受热度。<br>时尚流媒体。",
    heroDesc: "沉浸在独家剧集、激动人心的原创内容和影院级的刺激中。立即获取 Vidhub 应用，点燃您的观看列表 — 7天火热试用。",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "获取应用",
    btnInstall: "立即安装",
    sectionTitle: "正在热播 · 独家预览",
    bannerTitle: "Vidhub+ 会员",
    bannerDesc: "离线模式、HDR10+ 和无限下载。仅在我们的官方应用中。加入我们。",
    footerText: "© 2025 Vidhub 流媒体 — 故事燃烧的地方。版权所有。",
    footerExtra: "4K HDR | 移动应用无广告",
    toastDefault: "🔥 下载 Vidhub 应用 — 解锁热门独家内容和离线模式！",
    toastExclusive: "❤️‍🔥 此内容是 Vidhub 应用独享 — 立即获取！",
    trending: "热门 🔥",
    fresh: "新片",
    apkSize: "APK • XX MB",
    statUsers: "满意用户",
    statVideos: "下载量",
    statSync: "始终在线",
    feat1Title: "4K HDR 流媒体",
    feat1Desc: "支持 HDR10+ 的水晶般清晰画质，带来震撼视觉效果",
    feat2Title: "离线下载",
    feat2Desc: "下载您喜爱的内容，随时随地离线观看",
    feat3Title: "独家原创",
    feat3Desc: "您在任何地方都找不到的获奖原创内容",
    feat4Title: "无广告",
    feat4Desc: "在所有设备上享受不间断的观看体验",
    feat5Title: "多设备",
    feat5Desc: "在手机、平板、电视或网络浏览器上观看",
    feat6Title: "直播频道",
    feat6Desc: "访问100+直播频道和体育节目",
    feat7Title: "家庭共享",
    feat7Desc: "与多达6名家庭成员共享您的账户",
    feat8Title: "儿童模式",
    feat8Desc: "具有家长控制的安全观看体验",
    feat9Title: "下载",
    feat9Desc: "下载多达100个标题用于离线观看",
    feat10Title: "跳过开头",
    feat10Desc: "跳过片头字幕，直接进入精彩内容",
    feat11Title: "音频描述",
    feat11Desc: "为视障观众提供音频描述",
    feat12Title: "新发布",
    feat12Desc: "每周添加新电影和剧集"
  },
  ar: {
    title: "Vidhub",
    tagline: "شاهد بأناقة",
    subtitle: "شاهد في أي وقت وفي أي مكان",
    download: "تحميل التطبيق",
    explore: "استكشف الميزات",
    loading: "جاري التحميل...",
    downloading: "جاري تحميل Vidhub...",
    downloadStarted: "بدأ التحميل! تحقق من مجلد التنزيلات.",
    downloadError: "فشل التنزيل. يرجى المحاولة مرة أخرى.",
    features: "ميزات قوية",
    featuresSub: "كل ما تحتاجه لتجربة رائعة",
    heroBadge: "أحدث المحتوى · شغف لا محدود",
    heroTitle: "اشعر بالحرارة.<br>شاهد بأناقة.",
    heroDesc: "انغمز في المسلسلات الحصرية والمحتوى الأصلي المثير والمشاهد السينمائية المثيرة. احصل على تطبيق Vidhub الآن وأشعل قائمتك — 7 أيام تجربة مجانية.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "احصل على التطبيق",
    btnInstall: "التثبيت الآن",
    sectionTitle: "الآن ساخن · معاكسات حصرية",
    bannerTitle: "عضوية Vidhub+",
    bannerDesc: "وضع عدم الاتصال و HDR10+ وتنزيلات غير محدودة. فقط داخل تطبيقنا الرسمي. انضم إلى الحركة.",
    footerText: "© 2025 Vidhub للبث — حيث تحترق القصص بوضوح. جميع الحقوق محفوظة.",
    footerExtra: "4K HDR | لا إعلانات في التطبيق المحمول",
    toastDefault: "🔥 قم بتحميل تطبيق Vidhub — فتح الحصرية الساخنة ووضع عدم الاتصال!",
    toastExclusive: "❤️‍🔥 هذا المحتوى حصري لتطبيق Vidhub — احصل عليه الآن!",
    trending: "رائج 🔥",
    fresh: "اختيار جديد",
    apkSize: "APK • XX MB",
    statUsers: "المستخدمين سعداء",
    statVideos: "التنزيلات",
    statSync: "دائمًا متصل",
    feat1Title: "بث 4K HDR",
    feat1Desc: "جودة بلورية واضحة مع دعم HDR10+ لمرئيات مذهلة",
    feat2Title: "تنزيلات بدون إنترنت",
    feat2Desc: "قم بتنزيل المفضلة وشاهدها في أي مكان بدون إنترنت",
    feat3Title: "محتوى أصلي حصري",
    feat3Desc: "محتوى أصلي حائز على جوائز لن تجده في أي مكان آخر",
    feat4Title: "بدون إعلانات",
    feat4Desc: "تجربة مشاهدة غير متقطعة على جميع الأجهزة",
    feat5Title: "متعدد الأجهزة",
    feat5Desc: "شاهد على الهاتف أو الجهاز اللوحي أو التلفزيون أو متصفح الويب",
    feat6Title: "قنوات تلفزيونية مباشرة",
    feat6Desc: "الوصول إلى أكثر من 100 قناة تلفزيونية مباشرة والرياضة",
    feat7Title: "مشاركة عائلية",
    feat7Desc: "شارك حسابك مع ما يصل إلى 6 أفراد من العائلة",
    feat8Title: "وضع الأطفال",
    feat8Desc: "تجربة مشاهدة آمنة مع الرقابة الأبوية",
    feat9Title: "التنزيلات",
    feat9Desc: "قم بتنزيل ما يصل إلى 100 عنوان للمشاهدة بدون إنترنت",
    feat10Title: "تخطي المقدمة",
    feat10Desc: "تخطي الاعتمادات والانتقال مباشرة إلى الحدث",
    feat11Title: "أوصاف صوتية",
    feat11Desc: "أوصاف صوتية للمشاهدين ضعاف البصر",
    feat12Title: "إصدارات جديدة",
    feat12Desc: "أفلام وحلقات جديدة يتم إضافتها كل أسبوع"
  },
  hi: {
    title: "Vidhub",
    tagline: "स्टाइल में स्ट्रीम करें",
    subtitle: "कहीं भी कभी भी देखें",
    download: "ऐप डाउनलोड करें",
    explore: "सुविधाएं देखें",
    loading: "लोड हो रहा है...",
    downloading: "Vidhub डाउनलोड हो रहा है...",
    downloadStarted: "डाउनलोड शुरू! अपने डाउनलोड फ़ोल्डर की जांच करें।",
    downloadError: "डाउनलोड विफल। कृपया पुनः प्रयास करें।",
    features: "शक्तिशाली सुविधाएं",
    featuresSub: "शानदार अनुभव के लिए आपको जो कुछ भी चाहिए",
    heroBadge: "हॉट ड्रॉप्स · असीमित जुनून",
    heroTitle: "गर्मी महसूस करें.<br>स्टाइल में स्ट्रीम करें।",
    heroDesc: "एक्सक्लूसिव श्रृंखला, दिल को छू लेने वाली ओरिजिनल और सिनेमाई थ्रिल्स में डूबें। अभी Vidhub ऐप डाउनलोड करें और अपनी वॉचलिस्ट को जगाएं — 7 दिन की मुफ्त ट्रायल।",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "ऐप प्राप्त करें",
    btnInstall: "अभी इंस्टॉल करें",
    sectionTitle: "अभी गर्म · एक्सक्लूसिव पूर्वावलोकन",
    bannerTitle: "Vidhub+ सदस्यता",
    bannerDesc: "ऑफ़लाइन मोड, HDR10+ और असीमित डाउनलोड। केवल हमारी आधिकारिक ऐप में। आंदोलन में शामिल हों।",
    footerText: "© 2025 Vidhub स्ट्रीमिंग — जहां कहानियां जलती हैं। सर्वाधिकार सुरक्षित।",
    footerExtra: "4K HDR | मोबाइल ऐब पर कोई विज्ञापन नहीं",
    toastDefault: "🔥 Vidhub ऐप डाउनलोड करें — हॉट एक्सक्लूसिव और ऑफ़लाइन मोड अनलॉक करें!",
    toastExclusive: "❤️‍🔥 यह कंटेंट Vidhub ऐप के लिए एक्सक्लूसिव है — अभी प्राप्त करें!",
    trending: "ट्रेंडिंग 🔥",
    fresh: "नई पसंद",
    apkSize: "APK • XX MB",
    statUsers: "खुश उपयोगकर्ता",
    statVideos: "डाउनलोड",
    statSync: "हमेशा ऑनलाइन",
    feat1Title: "4K HDR स्ट्रीमिंग",
    feat1Desc: "HDR10+ समर्थन के साथ क्रिस्टल क्लियर क्वालिटी शानदार विज़ुअल के लिए",
    feat2Title: "ऑफ़लाइन डाउनलोड",
    feat2Desc: "अपने पसंदीदा डाउनलोड करें और बिना इंटरनेट के कहीं भी देखें",
    feat3Title: "एक्सक्लूसिव ओरिजिनल",
    feat3Desc: "पुरस्कार विजेता ओरिजिनल जो आपको कहीं और नहीं मिलेंगे",
    feat4Title: "विज्ञापन नहीं",
    feat4Desc: "सभी डिवाइस पर बिना रुके देखने का अनुभव",
    feat5Title: "मल्टी-डिवाइस",
    feat5Desc: "फोन, टैबलेट, TV या वेब ब्राउज़र पर देखें",
    feat6Title: "लाइव TV चैनल",
    feat6Desc: "100+ लाइव TV चैनल और स्पोर्ट्स तक पहुंच",
    feat7Title: "फैमिली शेयरिंग",
    feat7Desc: "अपने खाते को 6 फैमिली मेंबर के साथ शेयर करें",
    feat8Title: "किड्स मोड",
    feat8Desc: "पेरेंटल कंट्रोल के साथ सुरक्षित देखने का अनुभव",
    feat9Title: "डाउनलोड",
    feat9Desc: "ऑफ़लाइन देखने के लिए 100 शीर्षक तक डाउनलोड करें",
    feat10Title: "इंट्रो स्किप करें",
    feat10Desc: "ओपनिंग क्रेडिट को छोड़ें और सीधे एक्शन पर जाएं",
    feat11Title: "ऑडियो विवरण",
    feat11Desc: "दृष्टिबाधित दर्शकों के लिए ऑडियो विवरण",
    feat12Title: "नई रिलीज",
    feat12Desc: "हर हफ्ते नई फिल्में और एपिसोड जोड़े जाते हैं"
  },
  pt: {
    title: "Vidhub",
    tagline: "Assista com Estilo",
    subtitle: "Assista em Qualquer Lugar",
    download: "Baixar App",
    explore: "Explorar Recursos",
    loading: "Carregando...",
    downloading: "Baixando Vidhub...",
    downloadStarted: "Download iniciado! Verifique sua pasta de downloads.",
    downloadError: "Download falhou. Por favor, tente novamente.",
    features: "Recursos Poderosos",
    featuresSub: "Tudo que você precisa para uma experiência incrível",
    heroBadge: "Lançamentos quentes · Paixão ilimitada",
    heroTitle: "Sinta o calor.<br>Assista com estilo.",
    heroDesc: "Mergulhe em séries exclusivas, originais emocionantes e emoções de qualidade cinematográfica. Obtenha o aplicativo Vidhub agora e acenda sua lista — 7 dias de teste intensivo.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "Obter App",
    btnInstall: "Instalar Agora",
    sectionTitle: "Escaldante agora · prévias exclusivas",
    bannerTitle: "Associação Vidhub+",
    bannerDesc: "Modo offline, HDR10+ e downloads ilimitados. Apenas dentro do nosso aplicativo oficial. Junte-se ao movimento.",
    footerText: "© 2025 Vidhub Streaming — onde as histórias queimam intensamente. Todos os direitos reservados.",
    footerExtra: "4K HDR | Sem anúncios no aplicativo móvel",
    toastDefault: "🔥 Baixe o aplicativo Vidhub — desbloqueie exclusivos quentes e modo offline!",
    toastExclusive: "❤️‍🔥 Este conteúdo é exclusivo do aplicativo Vidhub — obtenha agora!",
    trending: "Em Alta 🔥",
    fresh: "Nova Escolha",
    apkSize: "APK • XX MB",
    statUsers: "Usuários Felizes",
    statVideos: "Downloads",
    statSync: "Sempre Online",
    feat1Title: "Streaming 4K HDR",
    feat1Desc: "Qualidade cristalina com suporte HDR10+ para visuais impressionantes",
    feat2Title: "Downloads Offline",
    feat2Desc: "Baixe seus favoritos e assista em qualquer lugar sem internet",
    feat3Title: "Originais Exclusivos",
    feat3Desc: "Originais premiados que você não encontrará em nenhum outro lugar",
    feat4Title: "Sem Anúncios",
    feat4Desc: "Experiência de visualização ininterrupta em todos os dispositivos",
    feat5Title: "Multi-Dispositivo",
    feat5Desc: "Assista no celular, tablet, TV ou navegador da web",
    feat6Title: "Canais de TV Ao Vivo",
    feat6Desc: "Acesso a mais de 100 canais de TV ao vivo e esportes",
    feat7Title: "Compartilhamento Familiar",
    feat7Desc: "Compartilhe sua conta com até 6 membros da família",
    feat8Title: "Modo Kids",
    feat8Desc: "Experiência de visualização segura com controles parentais",
    feat9Title: "Downloads",
    feat9Desc: "Baixe até 100 títulos para visualização offline",
    feat10Title: "Pular Intro",
    feat10Desc: "Pule os créditos de abertura e vá direto para a ação",
    feat11Title: "Descrições de Áudio",
    feat11Desc: "Descrições de áudio para espectadores com deficiência visual",
    feat12Title: "Novos Lançamentos",
    feat12Desc: "Novos filmes e episódios adicionados toda semana"
  }
};

// Native language names for the switcher
const languageNames = {
  en: "English",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  zh: "中文",
  ar: "العربية",
  hi: "हिन्दी",
  pt: "Português"
};

// Right-to-left languages
const rtlLanguages = ['ar'];
