// Multi-language translations for LeakVids APK Distribution
const translations = {
  en: {
    title: "LeakVids",
    tagline: "Intimate Moments, Leaked & Shared",
    subtitle: "Watch Anywhere, Anytime — Discover Exclusive Leaks",
    download: "Download App",
    explore: "Explore Features",
    loading: "Loading...",
    downloading: "Downloading LeakVids...",
    downloadStarted: "Download started! Check your downloads folder.",
    downloadError: "Download failed. Please try again.",
    features: "Powerful Features",
    featuresSub: "Everything you need for amazing experience",
    heroBadge: "Forbidden Treasures · Real Intimacy",
    heroTitle: "Feel the rush.<br>Explore the leaks.",
    heroDesc: "Dive into a world of exclusive, intimate moments, private captures, and authentic connections. Get the LeakVids app now and uncover what's been shared just for you — 7 days of thrilling access.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "Get the App",
    btnInstall: "Install Now",
    sectionTitle: "Sizzling now · exclusive previews",
    bannerTitle: "LeakVids+ Premium",
    bannerDesc: "Unlock unlimited access to exclusive private collections, offline mode, and 4K quality. Join the community of connoisseurs.",
    footerText: "© 2025 LeakVids Streaming — where private moments become shared passions. All rights reserved.",
    footerExtra: "4K HDR | No ads on mobile app",
    toastDefault: "🔥 Download LeakVids — access exclusive intimate leaks now!",
    toastExclusive: "💋 This private moment is only on LeakVids — get it now!",
    trending: "Trending leaks 🔥",
    fresh: "Fresh upload",
    apkSize: "APK • XX MB",
    statUsers: "Happy Users",
    statVideos: "Downloads",
    statSync: "Always Online",
    feat1Title: "4K HDR Streaming",
    feat1Desc: "Crystal clear quality with HDR10+ support for stunning visuals",
    feat2Title: "Offline Downloads",
    feat2Desc: "Download your favorites and watch anywhere without internet",
    feat3Title: "Exclusive Originals",
    feat3Desc: "Award-winning originals you won't find anywhere else",
    feat4Title: "No Ads",
    feat4Desc: "Uninterrupted viewing experience on all devices",
    feat5Title: "Multi-Device",
    feat5Desc: "Watch on phone, tablet, TV, or web browser",
    feat6Title: "Live TV Channels",
    feat6Desc: "Access to 100+ live TV channels and sports",
    feat7Title: "Family Sharing",
    feat7Desc: "Share your account with up to 6 family members",
    feat8Title: "Kids Mode",
    feat8Desc: "Safe viewing experience with parental controls",
    feat9Title: "Downloads",
    feat9Desc: "Download up to 100 titles for offline viewing",
    feat10Title: "Skip Intro",
    feat10Desc: "Skip opening credits and get straight to the action",
    feat11Title: "Audio Descriptions",
    feat11Desc: "Audio descriptions for visually impaired viewers",
    feat12Title: "New Releases",
    feat12Desc: "New movies and episodes added every week"
  },
  es: {
    title: "LeakVids",
    tagline: "Momentos Íntimos, Filtrados y Compartidos",
    subtitle: "Mira en Cualquier Lugar, en Cualquier Momento — Descubre Filtraciones Exclusivas",
    download: "Descargar App",
    explore: "Explorar Características",
    loading: "Cargando...",
    downloading: "Descargando LeakVids...",
    downloadStarted: "¡Descarga iniciada! Revisa tu carpeta de descargas.",
    downloadError: "Descarga fallida. Por favor, inténtelo de nuevo.",
    features: "Características Potentes",
    featuresSub: "Todo lo que necesitas para una experiencia increíble",
    heroBadge: "Tesoros Prohibidos · Intimidad Real",
    heroTitle: "Siente la emoción.<br>Explora las filtraciones.",
    heroDesc: "Sumérgete en un mundo de momentos íntimos exclusivos, capturas privadas y conexiones auténticas. Obtén la aplicación LeakVids ahora y descubre lo que han compartido solo para ti — 7 días de acceso emocionante.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "Obtener la App",
    btnInstall: "Instalar Ahora",
    sectionTitle: "Ardiendo ahora · vistas previas exclusivas",
    bannerTitle: "LeakVids+ Premium",
    bannerDesc: "Acceso ilimitado a colecciones privadas exclusivas, modo sin conexión y calidad 4K. Únete a la comunidad de conocedores.",
    footerText: "© 2025 LeakVids Streaming — donde los momentos privados se convierten en pasiones compartidas. Todos los derechos reservados.",
    footerExtra: "4K HDR | Sin anuncios en la aplicación móvil",
    toastDefault: "🔥 Descarga LeakVids — accede a filtraciones íntimas exclusivas ahora.",
    toastExclusive: "💋 Este momento privado solo está en LeakVids — consíguelo ahora.",
    trending: "Filtraciones tendencia 🔥",
    fresh: "Subida reciente",
    apkSize: "APK • XX MB",
    statUsers: "Usuarios Felices",
    statVideos: "Descargas",
    statSync: "Siempre Online",
    feat1Title: "Streaming en 4K HDR",
    feat1Desc: "Calidad cristalina con soporte HDR10+ para visuales impresionantes",
    feat2Title: "Descargas Sin Conexión",
    feat2Desc: "Descarga tus favoritos y mira donde sea sin internet",
    feat3Title: "Originales Exclusivos",
    feat3Desc: "Originales premiados que no encontrarás en ningún otro lugar",
    feat4Title: "Sin Anuncios",
    feat4Desc: "Experiencia de visualización ininterrumpida en todos los dispositivos",
    feat5Title: "Multi-Dispositivo",
    feat5Desc: "Mira en teléfono, tableta, TV o navegador web",
    feat6Title: "Canales de TV en Vivo",
    feat6Desc: "Acceso a más de 100 canales de TV en vivo y deportes",
    feat7Title: "Compartir en Familia",
    feat7Desc: "Comparte tu cuenta con hasta 6 miembros de la familia",
    feat8Title: "Modo Niños",
    feat8Desc: "Experiencia de visualización segura con controles parentales",
    feat9Title: "Descargas",
    feat9Desc: "Descarga hasta 100 títulos para ver sin conexión",
    feat10Title: "Saltar Intro",
    feat10Desc: "Salta los créditos de apertura y ve directo a la acción",
    feat11Title: "Descripciones de Audio",
    feat11Desc: "Descripciones de audio para espectadores con discapacidad visual",
    feat12Title: "Nuevos Lanzamientos",
    feat12Desc: "Nuevas películas y episodios añadidos cada semana"
  },
  fr: {
    title: "LeakVids",
    tagline: "Moments Intimes, Partagés et Révélés",
    subtitle: "Regardez N'importe Où, N'importe Quand — Découvrez les Fuites Exclusives",
    download: "Télécharger App",
    explore: "Explorer les Fonctionnalités",
    loading: "Chargement...",
    downloading: "Téléchargement LeakVids...",
    downloadStarted: "Téléchargement démarré! Vérifiez votre dossier de téléchargement.",
    downloadError: "Téléchargement échoué. Veuillez réessayer.",
    features: "Fonctionnalités Puissantes",
    featuresSub: "Tout ce dont vous avez besoin pour une expérience incroyable",
    heroBadge: "Trésors Interdits · Intimité Réelle",
    heroTitle: "Ressentez l'émotion.<br>Explorez les fuites.",
    heroDesc: "Plongez dans un univers de moments intimes exclusifs, de captures privées et de connexions authentiques. Obtenez l'application LeakVids maintenant et découvrez ce qui a été partagé rien que pour vous — 7 jours d'accès palpitant.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "Obtenir l'App",
    btnInstall: "Installer Maintenant",
    sectionTitle: "Brûlant maintenant · aperçus exclusifs",
    bannerTitle: "LeakVids+ Premium",
    bannerDesc: "Accès illimité à des collections privées exclusives, mode hors ligne et qualité 4K. Rejoignez la communauté des connaisseurs.",
    footerText: "© 2025 LeakVids Streaming — où les moments privés deviennent des passions partagées. Tous droits réservés.",
    footerExtra: "4K HDR | Pas de publicités sur l'application mobile",
    toastDefault: "🔥 Téléchargez LeakVids — accédez dès maintenant à des fuites intimes exclusives.",
    toastExclusive: "💋 Ce moment privé n'est que sur LeakVids — obtenez-le maintenant.",
    trending: "Fuites tendance 🔥",
    fresh: "Nouveau téléchargement",
    apkSize: "APK • XX MB",
    statUsers: "Utilisateurs Heureux",
    statVideos: "Téléchargements",
    statSync: "Toujours en Ligne",
    feat1Title: "Streaming 4K HDR",
    feat1Desc: "Qualité cristalline avec support HDR10+ pour des visuels époustouflants",
    feat2Title: "Téléchargements Hors Ligne",
    feat2Desc: "Téléchargez vos favoris et regardez n'importe où sans internet",
    feat3Title: "Originaux Exclusifs",
    feat3Desc: "Originaux primés que vous ne trouverez nulle part ailleurs",
    feat4Title: "Sans Publicités",
    feat4Desc: "Expérience de visualisation ininterrompue sur tous les appareils",
    feat5Title: "Multi-Appareil",
    feat5Desc: "Regardez sur téléphone, tablette, TV ou navigateur web",
    feat6Title: "Chaînes TV en Direct",
    feat6Desc: "Accès à plus de 100 chaînes TV en direct et sports",
    feat7Title: "Partage Famille",
    feat7Desc: "Partagez votre compte avec jusqu'à 6 membres de famille",
    feat8Title: "Mode Enfants",
    feat8Desc: "Expérience de visualisation sécurisée avec contrôles parentaux",
    feat9Title: "Téléchargements",
    feat9Desc: "Téléchargez jusqu'à 100 titres pour regarder hors ligne",
    feat10Title: "Skip Intro",
    feat10Desc: "Sautez les génériques et allez directement à l'action",
    feat11Title: "Descriptions Audio",
    feat11Desc: "Descriptions audio pour les spectateurs malvoyants",
    feat12Title: "Nouvelles Sorties",
    feat12Desc: "Nouveaux films et épisodes ajoutés chaque semaine"
  },
  de: {
    title: "LeakVids",
    tagline: "Intime Momente, Geteilt und Durchgesickert",
    subtitle: "Überall und jederzeit sehen — Entdecke exklusive Leaks",
    download: "App Herunterladen",
    explore: "Funktionen Erkunden",
    loading: "Laden...",
    downloading: "LeakVids herunterladen...",
    downloadStarted: "Download gestartet! Überprüfen Sie Ihren Download-Ordner.",
    downloadError: "Download fehlgeschlagen. Bitte versuchen Sie es erneut.",
    features: "Leistungsstarke Funktionen",
    featuresSub: "Alles was Sie für eine tolle Erfahrung brauchen",
    heroBadge: "Verbotene Schätze · Echte Intimität",
    heroTitle: "Spüre den Nervenkitzel.<br>Erkunde die Leaks.",
    heroDesc: "Tauche ein in eine Welt exklusiver intimer Momente, privater Aufnahmen und authentischer Verbindungen. Hol dir die LeakVids App jetzt und entdecke, was nur für dich geteilt wurde — 7 Tage spannenden Zugang.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "App Holen",
    btnInstall: "Jetzt Installieren",
    sectionTitle: "Heiß jetzt · exklusive Vorschauen",
    bannerTitle: "LeakVids+ Premium",
    bannerDesc: "Unbegrenzter Zugang zu exklusiven privaten Kollektionen, Offline-Modus und 4K-Qualität. Werde Teil der Gemeinschaft der Kenner.",
    footerText: "© 2025 LeakVids Streaming — wo private Momente zu geteilten Leidenschaften werden. Alle Rechte vorbehalten.",
    footerExtra: "4K HDR | Keine Werbung in der mobilen App",
    toastDefault: "🔥 Lade LeakVids herunter — erhalte jetzt Zugang zu exklusiven intimen Leaks.",
    toastExclusive: "💋 Dieser private Moment ist nur auf LeakVids — hol ihn dir jetzt.",
    trending: "Trend-Leaks 🔥",
    fresh: "Neuer Upload",
    apkSize: "APK • XX MB",
    statUsers: "Glückliche Benutzer",
    statVideos: "Downloads",
    statSync: "Immer Online",
    feat1Title: "4K HDR Streaming",
    feat1Desc: "Kristallklare Qualität mit HDR10+ Unterstützung für atemberaubende Bilder",
    feat2Title: "Offline Downloads",
    feat2Desc: "Laden Sie Ihre Favoriten herunter und schauen Sie überall ohne Internet",
    feat3Title: "Exklusive Originale",
    feat3Desc: "Ausgezeichnete Originale, die Sie nirgendwo anders finden",
    feat4Title: "Keine Werbung",
    feat4Desc: "Unterbrechungsfreies Seherlebnis auf allen Geräten",
    feat5Title: "Multi-Gerät",
    feat5Desc: "Schauen Sie auf Telefon, Tablet, TV oder Webbrowser",
    feat6Title: "Live-TV-Kanäle",
    feat6Desc: "Zugriff auf über 100 Live-TV-Kanäle und Sport",
    feat7Title: " Familienfreigabe",
    feat7Desc: "Teilen Sie Ihr Konto mit bis zu 6 Familienmitgliedern",
    feat8Title: "Kindermodus",
    feat8Desc: "Sicheres Seherlebnis mit Elternkontrollen",
    feat9Title: "Downloads",
    feat9Desc: "Laden Sie bis zu 100 Titel für das Offline-Ansehen herunter",
    feat10Title: "Intro Überspringen",
    feat10Desc: "Überspringen Sie den Abspann und kommen Sie direkt zum Action",
    feat11Title: "Audiobeschreibungen",
    feat11Desc: "Audiobeschreibungen für sehbehinderte Zuschauer",
    feat12Title: "Neuerscheinungen",
    feat12Desc: "Jede Woche werden neue Filme und Episoden hinzugefügt"
  },
  zh: {
    title: "LeakVids",
    tagline: "私密时刻，泄露与分享",
    subtitle: "随时随地观看 — 发现独家泄露内容",
    download: "下载应用",
    explore: "探索功能",
    loading: "加载中...",
    downloading: "正在下载 LeakVids...",
    downloadStarted: "下载已开始！请检查您的下载文件夹。",
    downloadError: "下载失败。请重试。",
    features: "强大功能",
    featuresSub: "出色体验所需的一切",
    heroBadge: "禁忌宝藏 · 真实亲密",
    heroTitle: "感受激情。<br>探索泄露。",
    heroDesc: "沉浸在一个充满独家私密时刻、私人拍摄和真实连接的世界。立即获取 LeakVids 应用，发现专为您分享的内容 — 7天刺激体验。",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "获取应用",
    btnInstall: "立即安装",
    sectionTitle: "正在热播 · 独家预览",
    bannerTitle: "LeakVids+ 高级版",
    bannerDesc: "解锁无限访问独家私密合集、离线模式和4K画质。加入鉴赏家社区。",
    footerText: "© 2025 LeakVids 流媒体 — 私密时刻成为共享激情的地方。版权所有。",
    footerExtra: "4K HDR | 移动应用无广告",
    toastDefault: "🔥 下载 LeakVids — 立即访问独家私密泄露内容！",
    toastExclusive: "💋 此私密时刻仅在 LeakVids 上 — 立即获取！",
    trending: "热门泄露 🔥",
    fresh: "最新上传",
    apkSize: "APK • XX MB",
    statUsers: "满意用户",
    statVideos: "下载量",
    statSync: "始终在线",
    feat1Title: "4K HDR 流媒体",
    feat1Desc: "支持 HDR10+ 的水晶般清晰画质，带来震撼视觉效果",
    feat2Title: "离线下载",
    feat2Desc: "下载您喜爱的内容，随时随地离线观看",
    feat3Title: "独家原创",
    feat3Desc: "您在任何地方都找不到的获奖原创内容",
    feat4Title: "无广告",
    feat4Desc: "在所有设备上享受不间断的观看体验",
    feat5Title: "多设备",
    feat5Desc: "在手机、平板、电视或网络浏览器上观看",
    feat6Title: "直播频道",
    feat6Desc: "访问100+直播频道和体育节目",
    feat7Title: "家庭共享",
    feat7Desc: "与多达6名家庭成员共享您的账户",
    feat8Title: "儿童模式",
    feat8Desc: "具有家长控制的安全观看体验",
    feat9Title: "下载",
    feat9Desc: "下载多达100个标题用于离线观看",
    feat10Title: "跳过开头",
    feat10Desc: "跳过片头字幕，直接进入精彩内容",
    feat11Title: "音频描述",
    feat11Desc: "为视障观众提供音频描述",
    feat12Title: "新发布",
    feat12Desc: "每周添加新电影和剧集"
  },
  ar: {
    title: "LeakVids",
    tagline: "لحظات حميمية، مسربة ومشاركة",
    subtitle: "شاهد في أي وقت وفي أي مكان — اكتشف التسريبات الحصرية",
    download: "تحميل التطبيق",
    explore: "استكشف الميزات",
    loading: "جاري التحميل...",
    downloading: "جاري تحميل LeakVids...",
    downloadStarted: "بدأ التحميل! تحقق من مجلد التنزيلات.",
    downloadError: "فشل التنزيل. يرجى المحاولة مرة أخرى.",
    features: "ميزات قوية",
    featuresSub: "كل ما تحتاجه لتجربة رائعة",
    heroBadge: "كنوز ممنوعة · حميمية حقيقية",
    heroTitle: "اشعر بالإثارة.<br>استكشف التسريبات.",
    heroDesc: "انغمس في عالم من اللحظات الحميمية الحصرية، واللقطات الخاصة، والروابط الحقيقية. احصل على تطبيق LeakVids الآن واكتشف ما تم مشاركته خصيصًا لك — 7 أيام من الوصول المثير.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "احصل على التطبيق",
    btnInstall: "التثبيت الآن",
    sectionTitle: "الآن ساخن · معاينات حصرية",
    bannerTitle: "LeakVids+ بريميوم",
    bannerDesc: "فتح الوصول غير المحدود إلى مجموعات خاصة حصرية، وضع عدم الاتصال وجودة 4K. انضم إلى مجتمع الخبراء.",
    footerText: "© 2025 LeakVids للبث — حيث تصبح اللحظات الخاصة شغفًا مشتركًا. جميع الحقوق محفوظة.",
    footerExtra: "4K HDR | لا إعلانات في التطبيق المحمول",
    toastDefault: "🔥 حمل LeakVids — احصل على تسريبات حميمية حصرية الآن.",
    toastExclusive: "💋 هذه اللحظة الخاصة متوفرة فقط على LeakVids — احصل عليها الآن.",
    trending: "تسريبات رائجة 🔥",
    fresh: "تحميل جديد",
    apkSize: "APK • XX MB",
    statUsers: "المستخدمين سعداء",
    statVideos: "التنزيلات",
    statSync: "دائمًا متصل",
    feat1Title: "بث 4K HDR",
    feat1Desc: "جودة بلورية واضحة مع دعم HDR10+ لمرئيات مذهلة",
    feat2Title: "تنزيلات بدون إنترنت",
    feat2Desc: "قم بتنزيل المفضلة وشاهدها في أي مكان بدون إنترنت",
    feat3Title: "محتوى أصلي حصري",
    feat3Desc: "محتوى أصلي حائز على جوائز لن تجده في أي مكان آخر",
    feat4Title: "بدون إعلانات",
    feat4Desc: "تجربة مشاهدة غير متقطعة على جميع الأجهزة",
    feat5Title: "متعدد الأجهزة",
    feat5Desc: "شاهد على الهاتف أو الجهاز اللوحي أو التلفزيون أو متصفح الويب",
    feat6Title: "قنوات تلفزيونية مباشرة",
    feat6Desc: "الوصول إلى أكثر من 100 قناة تلفزيونية مباشرة والرياضة",
    feat7Title: "مشاركة عائلية",
    feat7Desc: "شارك حسابك مع ما يصل إلى 6 أفراد من العائلة",
    feat8Title: "وضع الأطفال",
    feat8Desc: "تجربة مشاهدة آمنة مع الرقابة الأبوية",
    feat9Title: "التنزيلات",
    feat9Desc: "قم بتنزيل ما يصل إلى 100 عنوان للمشاهدة بدون إنترنت",
    feat10Title: "تخطي المقدمة",
    feat10Desc: "تخطي الاعتمادات والانتقال مباشرة إلى الحدث",
    feat11Title: "أوصاف صوتية",
    feat11Desc: "أوصاف صوتية للمشاهدين ضعاف البصر",
    feat12Title: "إصدارات جديدة",
    feat12Desc: "أفلام وحلقات جديدة يتم إضافتها كل أسبوع"
  },
  hi: {
    title: "LeakVids",
    tagline: "अंतरंग पल, लीक और साझा",
    subtitle: "कहीं भी कभी भी देखें — अनन्य लीक खोजें",
    download: "ऐप डाउनलोड करें",
    explore: "सुविधाएं देखें",
    loading: "लोड हो रहा है...",
    downloading: "LeakVids डाउनलोड हो रहा है...",
    downloadStarted: "डाउनलोड शुरू! अपने डाउनलोड फ़ोल्डर की जांच करें।",
    downloadError: "डाउनलोड विफल। कृपया पुनः प्रयास करें।",
    features: "शक्तिशाली सुविधाएं",
    featuresSub: "शानदार अनुभव के लिए आपको जो कुछ भी चाहिए",
    heroBadge: "वर्जित खजाने · वास्तविक अंतरंगता",
    heroTitle: "रोमांच महसूस करें.<br>लीक का अन्वेषण करें।",
    heroDesc: "अनन्य अंतरंग पलों, निजी कैप्चर और प्रामाणिक जुड़ाव की दुनिया में गोता लगाएँ। अभी LeakVids ऐप प्राप्त करें और जानें कि सिर्फ आपके लिए क्या साझा किया गया है — 7 दिनों का रोमांचक एक्सेस।",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "ऐप प्राप्त करें",
    btnInstall: "अभी इंस्टॉल करें",
    sectionTitle: "अभी गर्म · विशेष पूर्वावलोकन",
    bannerTitle: "LeakVids+ प्रीमियम",
    bannerDesc: "अनन्य निजी संग्रह, ऑफ़लाइन मोड और 4K गुणवत्ता तक असीमित पहुंच खोलें। पारखियों के समुदाय में शामिल हों।",
    footerText: "© 2025 LeakVids स्ट्रीमिंग — जहां निजी पल साझा जुनून बन जाते हैं। सर्वाधिकार सुरक्षित।",
    footerExtra: "4K HDR | मोबाइल ऐप पर कोई विज्ञापन नहीं",
    toastDefault: "🔥 LeakVids डाउनलोड करें — अब अनन्य अंतरंग लीक तक पहुंचें।",
    toastExclusive: "💋 यह निजी पल केवल LeakVids पर है — इसे अभी प्राप्त करें।",
    trending: "ट्रेंडिंग लीक 🔥",
    fresh: "नया अपलोड",
    apkSize: "APK • XX MB",
    statUsers: "खुश उपयोगकर्ता",
    statVideos: "डाउनलोड",
    statSync: "हमेशा ऑनलाइन",
    feat1Title: "4K HDR स्ट्रीमिंग",
    feat1Desc: "HDR10+ समर्थन के साथ क्रिस्टल क्लियर क्वालिटी शानदार विज़ुअल के लिए",
    feat2Title: "ऑफ़लाइन डाउनलोड",
    feat2Desc: "अपने पसंदीदा डाउनलोड करें और बिना इंटरनेट के कहीं भी देखें",
    feat3Title: "एक्सक्लूसिव ओरिजिनल",
    feat3Desc: "पुरस्कार विजेता ओरिजिनल जो आपको कहीं और नहीं मिलेंगे",
    feat4Title: "विज्ञापन नहीं",
    feat4Desc: "सभी डिवाइस पर बिना रुके देखने का अनुभव",
    feat5Title: "मल्टी-डिवाइस",
    feat5Desc: "फोन, टैबलेट, TV या वेब ब्राउज़र पर देखें",
    feat6Title: "लाइव TV चैनल",
    feat6Desc: "100+ लाइव TV चैनल और स्पोर्ट्स तक पहुंच",
    feat7Title: "फैमिली शेयरिंग",
    feat7Desc: "अपने खाते को 6 फैमिली मेंबर के साथ शेयर करें",
    feat8Title: "किड्स मोड",
    feat8Desc: "पेरेंटल कंट्रोल के साथ सुरक्षित देखने का अनुभव",
    feat9Title: "डाउनलोड",
    feat9Desc: "ऑफ़लाइन देखने के लिए 100 शीर्षक तक डाउनलोड करें",
    feat10Title: "इंट्रो स्किप करें",
    feat10Desc: "ओपनिंग क्रेडिट को छोड़ें और सीधे एक्शन पर जाएं",
    feat11Title: "ऑडियो विवरण",
    feat11Desc: "दृष्टिबाधित दर्शकों के लिए ऑडियो विवरण",
    feat12Title: "नई रिलीज",
    feat12Desc: "हर हफ्ते नई फिल्में और एपिसोड जोड़े जाते हैं"
  },
  pt: {
    title: "LeakVids",
    tagline: "Momentos Íntimos, Vazados e Compartilhados",
    subtitle: "Assista em Qualquer Lugar, a Qualquer Hora — Descubra Vazamentos Exclusivos",
    download: "Baixar App",
    explore: "Explorar Recursos",
    loading: "Carregando...",
    downloading: "Baixando LeakVids...",
    downloadStarted: "Download iniciado! Verifique sua pasta de downloads.",
    downloadError: "Download falhou. Por favor, tente novamente.",
    features: "Recursos Poderosos",
    featuresSub: "Tudo que você precisa para uma experiência incrível",
    heroBadge: "Tesouros Proibidos · Intimidade Real",
    heroTitle: "Sinta a emoção.<br>Explore os vazamentos.",
    heroDesc: "Mergulhe em um mundo de momentos íntimos exclusivos, capturas privadas e conexões autênticas. Obtenha o aplicativo LeakVids agora e descubra o que foi compartilhado só para você — 7 dias de acesso emocionante.",
    btnAppStore: "App Store",
    btnGooglePlay: "Google Play",
    btnDownload: "Obter App",
    btnInstall: "Instalar Agora",
    sectionTitle: "Escaldante agora · prévias exclusivas",
    bannerTitle: "LeakVids+ Premium",
    bannerDesc: "Acesso ilimitado a coleções privadas exclusivas, modo offline e qualidade 4K. Junte-se à comunidade de conhecedores.",
    footerText: "© 2025 LeakVids Streaming — onde momentos privados se tornam paixões compartilhadas. Todos os direitos reservados.",
    footerExtra: "4K HDR | Sem anúncios no aplicativo móvel",
    toastDefault: "🔥 Baixe LeakVids — acesse vazamentos íntimos exclusivos agora.",
    toastExclusive: "💋 Este momento privado está apenas no LeakVids — obtenha agora.",
    trending: "Vazamentos em alta 🔥",
    fresh: "Upload recente",
    apkSize: "APK • XX MB",
    statUsers: "Usuários Felizes",
    statVideos: "Downloads",
    statSync: "Sempre Online",
    feat1Title: "Streaming 4K HDR",
    feat1Desc: "Qualidade cristalina com suporte HDR10+ para visuais impressionantes",
    feat2Title: "Downloads Offline",
    feat2Desc: "Baixe seus favoritos e assista em qualquer lugar sem internet",
    feat3Title: "Originais Exclusivos",
    feat3Desc: "Originais premiados que você não encontrará em nenhum outro lugar",
    feat4Title: "Sem Anúncios",
    feat4Desc: "Experiência de visualização ininterrupta em todos os dispositivos",
    feat5Title: "Multi-Dispositivo",
    feat5Desc: "Assista no celular, tablet, TV ou navegador da web",
    feat6Title: "Canais de TV Ao Vivo",
    feat6Desc: "Acesso a mais de 100 canais de TV ao vivo e esportes",
    feat7Title: "Compartilhamento Familiar",
    feat7Desc: "Compartilhe sua conta com até 6 membros da família",
    feat8Title: "Modo Kids",
    feat8Desc: "Experiência de visualização segura com controles parentais",
    feat9Title: "Downloads",
    feat9Desc: "Baixe até 100 títulos para visualização offline",
    feat10Title: "Pular Intro",
    feat10Desc: "Pule os créditos de abertura e vá direto para a ação",
    feat11Title: "Descrições de Áudio",
    feat11Desc: "Descrições de áudio para espectadores com deficiência visual",
    feat12Title: "Novos Lançamentos",
    feat12Desc: "Novos filmes e episódios adicionados toda semana"
  }
};

// Native language names for the switcher
const languageNames = {
  en: "English",
  es: "Español",
  fr: "Français",
  de: "Deutsch",
  zh: "中文",
  ar: "العربية",
  hi: "हिन्दी",
  pt: "Português"
};

// Right-to-left languages
const rtlLanguages = ['ar'];